# Generated by Django 3.0.6 on 2020-06-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('information', models.TextField()),
                ('safety', models.IntegerField(default=0)),
                ('entrance', models.CharField(max_length=7)),
            ],
        ),
    ]
