# Generated by Django 3.0.7 on 2020-06-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='krdaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kr_date', models.CharField(max_length=200)),
                ('kr_confirmed', models.CharField(max_length=200)),
                ('kr_death', models.CharField(max_length=200)),
                ('kr_candidate', models.CharField(max_length=200)),
                ('kr_negative', models.CharField(max_length=200)),
            ],
        ),
    ]
