# Generated by Django 3.0.7 on 2020-06-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='krdaily',
            name='kr_released',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
