# Generated by Django 3.0.7 on 2020-06-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_krdaily_kr_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('information', models.TextField()),
                ('safety', models.IntegerField(default=0)),
                ('entrance', models.CharField(max_length=7)),
            ],
        ),
    ]
